# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-06 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orginfo',
            options={'ordering': ['id'], 'verbose_name': '机构信息', 'verbose_name_plural': '机构信息'},
        ),
    ]
